## Broadlink HASS Module
## https://home-assistant.io/components/switch.broadlink/


##################################################
## Switches
##################################################

switch:
## LG Most Models Discrete Codes
## https://community.home-assistant.io/t/broadlink-rm-pro-and-a1-sensor/3678/111
- platform: broadlink
  host: !secret ip_broadlink
  mac: !secret mac_broadlink
  timeout: 60
  type: rm2_pro_plus
  switches:
    # TV
    tv_onoff:
      friendly_name: "TV"
      command_on:  'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABHpISEhMSETYTEhATEhQREhMSEDgRNxISEjcRNxE1EjcSNhM1EhISNhEUERETEhI1EjcSEhE4ExARNxI3ETYTERMSEQAFGAABIEgTAAwpAAEfSRIADQU='
    tv_hdmi1:
      friendly_name: "TV HDMI1"
      command_on:  'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      command_off: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
    tv_hdmi2:
      friendly_name: "TV HDMI2"
      command_on:  'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
    tv_antena:
      friendly_name: "TV Antena"
      command_on:  'JgBYAAABIpIRExITETgRExITERMSExEUETcSNxEUETcSNxI3ETcSNxI3ETgRNxI3EhMRExITERMSExITERMSExE4ETcSNxI3EQAFCgABIkkRAAwnAAEiSRIADQU='
      command_off: 'JgBYAAABIpIRExITETgRExITERMSExEUETcSNxEUETcSNxI3ETcSNxI3ETgRNxI3EhMRExITERMSExITERMSExE4ETcSNxI3EQAFCgABIkkRAAwnAAEiSRIADQU='
    tv_mute:
      friendly_name: "TV Mute"
      command_on:  'JgBQAAABIpITERITETcSExITERMSExETEjcSNxETEjcTNhE4ETcSNxI3ERMSExE4ERMSExETEhMRFBE3EjcSExE3EjcSNxE4EQAFCwABIkkSAA0FAAAAAAAAAAA='
      command_off: 'JgBYAAABIpITERITEjcRExITERQRExITEzUSNxITETgRNxQ1ETgRNxI3EhMRExQ1EhMRExITERMSExE4ETcSExE4ETcSNxI3EwAFCQABIkkSAAwoAAEiSRIADQU='
    tv_volume_down:
      friendly_name: "TV Volume Down"
      command_on:  'JgBQAAABIpIRExITETgRExITERMSExITETcSNxITETcSNxI3ETgRNxI3EjcRExITERQRExITERMSExETEjcSNxE4ETcSNxI3EQAFCgABIkkSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIpIRExITETgRExITERMSExITETcSNxITETcSNxI3ETgRNxI3EjcRExITERQRExITERMSExETEjcSNxE4ETcSNxI3EQAFCgABIkkSAA0FAAAAAAAAAAA='
    tv_volume_up:
      friendly_name: "TV Volume Up"
      command_on:  'JgBQAAABIpIRExITETgRExITERMSExETEjcSNxEUETcSNxI3ETcSNxITETgRExITERMSExEUERMSNxETEjcSNxE4ETcSNxI3EQAFCgABIkkSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABIpIRExITETgRExITERMSExETEjcSNxEUETcSNxI3ETcSNxITETgRExITERMSExEUERMSNxETEjcSNxE4ETcSNxI3EQAFCgABIkkSAA0FAAAAAAAAAAA='
    
    # AC
    ac_onoff:
      friendly_name: "AC"
      command_on:  ''
      command_off: 'JgDKAJCREjUUERI2EjYRExETEDcSEhETETcRExETETcRNxETETcQFBE2ETcSNhE2ExERNxI2EjYSEhETERMRExE3EhIRExE2ETcSNhETEhIRExETEhISEhISExESNhE2EjYSNhI2EK6QkRE2EhISNhI2EhISEhI2ERMRExI2ERMRExA3EjYRExI2EhIRNxE2EjYSNhISEjYRNhI2ERMSEhISEhIRNxETERMSNhE3EDcSEhETERMSEhISERMSEhETEzUSNhI1EjYSNhEADQUAAAAAAAAAAAAAAAAAAA=='
    ac_hot:
      friendly_name: "AC Hot"
      command_on:  'JgDKAI+SEjYQExI2EjYRExETETYSExETEDcSEhETEjYRNxAUEDcSEhETEjYRNxI2EDcUNBI2EDcRNxETERMRExETExESEhI2ERMSNhA3ETcRNxETEBQQFBA3ERMRExETERMRNxE2Ea6PkRE3ERMRNxI1ERMRExE3EhISEhE3EhIRExI1ETcSEhI2ERMSEhE3ETYSNhI2ETYSNhE3EjYRExESEhISEhETEhIRNxETETcRNxE2ETcSEhETERMSNhAUERMQFBAUETYTNRIADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: ''
    ac_cold:
      friendly_name: "AC Cold"
      command_on:  'JgDKAJCREzUTERM1EzQRExMREzUTERMREzUTERMREzUSNRMRETcRNxMREzURNhE3EzUTNBE3ExETNRETExETERETExESEhMRExERExM1EBQQFBATERMTNRM1ETcSEhE3EjURNxE3EK6PkhI1ERMRNxM1EhIRExA3ERMRExM1ExERExE3EjURExE3EzUTERM1EzQTNRM1ETYTNRMREjYTERETExETERETERMRExETERMRNhETERMRExMRETcRNxM0ERQSNRE3EzUSNREADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: ''


##################################################
## Scripts
##################################################

script:
  ir_learn:
    alias: Learn IR
    sequence:
      - service: broadlink.learn_command_192_168_0_3

